### ISSUE TITLE
Vous pouvez mettre le projet dans l'entité https://github.com/HE-Arc ?

### ISSUE THREAD

**Issue by grunenwald** [HE-Arc/SimpleTroc#13]

**Comment by johndacost** [comment]
@grunenwald  Y a-t-il moyen de le faire depuis le github ou on doit t-on passer par la commande `git remote set-url https://github.com/USERNAME/REPOSITORY.git` ?

**Comment by 73VW** [comment]
@grunenwald @johndacost C'est fait
Par contre on a plus accès au settings du repo du coup

**Comment by grunenwald** [comment]
Je vous ai remis admin, ça joue pour les settings ?

**Comment by 73VW** [comment]
@grunenwald c'est parfait! merci beaucoup!
