### ISSUE TITLE
Automate everything

### ISSUE THREAD

**Issue by 73VW** [HE-Arc/SimpleTroc#23]
Find a solution to have an autodeploy solution

**Comment by 73VW** [comment]
Still have to find a way to use a database on heroku. Databases don't work for the moment.

**Comment by 73VW** [comment]
Database troubles are now solved
Filesystem is not reliable in heroku. Have to find a way to upload pictures somewhere else.
Ping @johndacost

**Comment by johndacost** [comment]
Use Dropbox driver instead local system...

**Comment by 73VW** [comment]
> I will try a little trick with the config/filesystems to fix this

Okay, thanks, waiting for this.

**Comment by johndacost** [comment]
@73VW So I change the local driver to dropbox driver. I think now it will be ok with heroku! Just update the .env : 
DROPBOX_APP_SECRET=...
DROPBOX_TOKEN=...
