### ISSUE TITLE
Make the cart user

### ISSUE THREAD

**Issue by johndacost** [HE-Arc/SimpleTroc#46]
The user can add or remove some item.

Eloquent Relationships :

- A cart belongsTo an user
- A user hasOne cart

**Comment by 73VW** [comment]
Do you really want to store the cart in the database? I don't understand the point of doing this. Can you explain me? (Here or on Gitter)

**Comment by johndacost** [comment]
Like Zalando, when you browsing some article and you want to keep them (like favorite item that it want to see later before to buy or troc them.). When we create a user, we have to create a cart for this user.

**Comment by 73VW** [comment]
Okay, I see, thanks
